berachain/bera-reth

- Makefile
The Makefile referenced features (jemalloc, asm-keccak, min-debug-logs) that don't exist in the current Cargo.toml, causing cross-compilation builds to fail. Remove these features to fix Docker workflow.
> Fix Docker build by removing non-existent Cargo features

- Cargo.lock
- Cargo.toml
- Makefile
- src/chainspec/mod.rs
- Switch reth dependencies from rezbera/reth to berachain/reth prague1-berachain-reth branch
- Add alloy git patches to fix compatibility issues
- Update chainspec API to match new trait signatures
Recent upstream reth changes activated alloy git patches and updated alloy-trie from 0.8.1 to 0.9.0, causing build failures. The berachain/reth prague1-berachain-reth branch includes these necessary patches.
**Key Changes:**
- All reth dependencies now point to `berachain/reth` `prague1-berachain-reth` branch 
- Added alloy git patches (rev `08fa016ed950b6e65f810fc9cdef7cf38fbc63f6`) to resolve `TrieAccount` trait bound errors
- Updated `next_block_base_fee` to return `Option<u64>` per new `EthChainSpec` trait
- Switch to `calc_next_block_base_fee` from `alloy-eips` for better consistency …
> feat: update reth dependencies to berachain/reth prague1-berachain-reth

- Cargo.lock
- Cargo.toml
- Updated all reth dependencies from berachain/reth fork to upstream paradigmxyz/reth at commit 07b19553a14fe9c2e6c36a7c3b8b793bbc9c50a7
- Updated alloy dependencies to their latest versions:
- alloy-consensus: 1.0.9 → 1.0.13
- alloy-eips: 1.0.9 → 1.0.13
- alloy-genesis: 1.0.9 → 1.0.13
- alloy-primitives: 1.0.9 → 1.2.1
- alloy-rpc-types: 1.0.9 → 1.0.13
- Removed alloy patches that are no longer needed
- Verified build and tests pass with updated dependencies
> feat: update reth and alloy dependencies to latest versions

- Cargo.lock
- Cargo.toml
- src/chainspec/mod.rs
- src/consensus/mod.rs
- src/engine/mod.rs
- src/engine/payload.rs
- src/engine/rpc.rs
- src/engine/validator.rs
- src/node/evm/executor.rs
- src/node/mod.rs
- src/transaction/pol.rs
Implement custom Berachain consensus validation and upgrade reth dependencies.
- **Custom Consensus**: `BerachainBeaconConsensus` delegates to Ethereum consensus while validating PoL transactions for Prague1 blocks
- **PoL Validation**: Hash-based validation ensuring first transaction is PoL and matches canonical structure
- **Engine API**: Extract Prague1 validation logic and add proposer pubkey validation with comprehensive tests
- **Reth Upgrade**: Update dependencies to ac2974867f763ed for latest features and stability
- **Chainspec**: Enhanced Prague1 configuration and PoL contract integration
> feat: implement custom consensus with PoL validation and reth upgrades

- src/primitives/header.rs
- Implements backwards compatible Compact trait for BerachainHeader using reth's extension pattern
- Adds CompactBerachainHeader and BerachainHeaderExt structs following reth's proven design
- Ensures storage efficiency where headers without prev_proposer_pubkey don't waste space
> fix: implement backwards compatible header compaction

- src/transaction/txtype.rs
- Fixes panic `"Unsupported BerachainTxType extended identifier: 3"` during transaction processing
- Adds missing support for EIP-4844 (blob) and EIP-7702 (set code) transaction types in compact encoding
- Ensures complete backwards compatibility with existing Ethereum transaction data
> fix: handle EIP-4844 and EIP-7702 transaction types in compact encoding

- Cargo.lock
- Cargo.toml
- src/rpc/api.rs
- src/rpc/mod.rs
- src/rpc/receipt.rs
- Update all reth dependencies to commit 58235419bb855728d9f2afbc8bd59cf8690e8804 (v1.6.0)
- Fix API compatibility issues with new reth version
- Update EthApiBuilder usage to use new_with_components pattern
- Resolve signers method disambiguation in EthTransactions trait
- Updated Cargo.toml with new reth commit hash across all dependencies
- Modified RPC API implementation to work with updated reth interfaces
- Cleaned up unused imports
> chore: update reth to commit 58235419bb855728d9f2afbc8bd59cf8690e8804

- src/transaction/mod.rs
- Changes POL transaction effective_gas_price() to return self.gas_price instead of 0
- Aligns with the effective gas price implementation used in bera-geth
> fix: use gas_price for POL transaction effective gas price

- Cross.toml
- Makefile
- Update Makefile to use 'cross' instead of 'cargo' for cross-compilation
- Add Cross.toml configuration with proper build dependencies
- Fixes aarch64-unknown-linux-gnu build failures in CI/CD workflow
The previous setup failed because cross-compilation requires specialized toolchains and Docker images that 'cross' provides. This change aligns with upstream Reth patterns and enables successful multi-architecture builds.
> ci: enable proper cross-compilation for release targets

- src/engine/rpc.rs
Fixes the exchange_capabilities method in the engine API to properly advertise Berachain-specific Prague1 fork extensions (engine_newPayloadV4P11, engine_forkchoiceUpdatedV3P11, engine_getPayloadV4P11). Previously, these capabilities were implemented but not advertised during capability negotiation, causing beacon-kit to log warnings about unsupported capabilities during startup. The implementation clones the base capabilities, adds the Berachain extensions, and returns the enhanced capability list to ensure proper integration with beacon-kit.
> fix: add Berachain-specific capabilities to engine API exchange

- src/main.rs
The CLI requires components to be passed in for code paths beyond building the node itself. 
In reth, usages can be started from here https://github.com/paradigmxyz/reth/blob/6923e051ee84fe9d7afd550e2852b0151c847785/crates/cli/commands/src/common.rs#L270-L272
Fixes correctness of CLI commands:
- `import`
- `re-execute`
- `stage`
> fix: use correct consensus in CLI components builder

- Cargo.lock
- Cargo.toml
- src/engine/payload.rs
This PR fixes payload_id generation to include the optional prev_proposer_pubkey field in the hash calculation. The current implementation was using the standard Ethereum payload_id function which does not account for the Berachain-specific prev_proposer_pubkey field, potentially causing payload conflicts when different proposer pubkeys are used for the same block parameters in Prague1 scenarios. This scenario is highly unlikely
NOTE: This does not get parity to the geth implementation as geth has different behaviour for nil withdrawals and also included a payload version byte, which reth doesn't have.
Fixes #68
> fix: include prev_proposer_pubkey in payload_id generation

- Cargo.lock
- Cargo.toml
- src/consensus/mod.rs
- src/engine/mod.rs
- src/engine/payload.rs
- src/engine/rpc.rs
- src/engine/validator.rs
- src/genesis/mod.rs
- src/main.rs
- src/node/mod.rs
- src/pool/transaction.rs
- src/primitives/header.rs
- src/primitives/mod.rs
- src/rpc/mod.rs
prompt
```
I am trying to upgrade my bera-reth, reth dependency to the latest reth version. I have started the changes, but i'm runnign into issues. I need to you to study all the commits between my last reth version and the current and then figure out the changes that need to be done to bera-reth to stay compatible without compiler issues. Spin up as many subagents as you need. I've tried started the changes but its tricky. Ultrathink.
You don't need to research the tags. Look at my staged changes to see the diff in reth commits. I'm technically still in the same reth version but trying to bump. Remember that I also have reth locally at ./reth
```
closes #65
> chore: upgrade reth dependency to 48941e6

- src/chainspec/mod.rs
- src/consensus/mod.rs
- src/genesis/mod.rs
- src/node/evm/executor.rs
This PR addresses several code review recommendations to improve code clarity and maintainability:
• Replace `unwrap_or_default()` with `unwrap()` for terminal_total_difficulty since validation already ensures it's not None
• Remove misleading log messages about defaults when no defaults are actually used  
• Remove the unused InvalidActivationTime error variant
• Add inline documentation for chain specification fields
• Enhance hardfork display to show Prague1 configuration details (activation time, base fee denominator, minimum base fee, and PoL distributor address) during startup logging
• Show "Prague1 Misconfigured" if Prague1 is not properly configured as a timestamp-based fork
> fix: chainspec genesis parsing nits and add more startup logging for prague1

- Cargo.lock
- Cargo.toml
Bumps the crate version to v1.0.0-rc.9 in preparation for the next release candidate.
- Update version in `Cargo.toml` from `1.0.0-rc.8` to `1.0.0-rc.9`
- Update `Cargo.lock` accordingly
1. Create and push git tag: `git tag v1.0.0-rc.9 && git push origin v1.0.0-rc.9`
2. Monitor release workflow in Actions
3. Review and publish the generated release
> chore: bump version to 1.0.0-rc.9

- .github/workflows/docker.yml
- Restrict `:latest` Docker tag to only apply to exact `vx.y.z` semantic version tags
- Previous logic only excluded `-rc` suffixes, now excludes any non-semantic version patterns
- Prevents accidental `:latest` updates from alpha, beta, RC, or other pre-release tags
- Updated Docker workflow condition from `\!contains(github.ref, '-rc')` to strict pattern matching
- Now requires exact `vx.y.z` format with no additional suffixes (`-`, `+`, `_`)
> chore: protect :latest docker tag from accidental updates

- tests/e2e/gas_limit_regression_test.rs
- tests/e2e/mod.rs
- tests/e2e/transaction_tests.rs
Adds a strict regression test to ensure REVM's 30M system call gas limit remains unchanged for PoL transactions. This addresses an audit concern about gas limit validation consistency.
The test:
- Deploys a custom PoL distributor contract that validates exactly 29,999,646 gas remains at execution time
- Fails if REVM's 30M system call limit changes or gas consumption patterns shift
- Provides early detection of breaking changes in gas handling
Closes https://github.com/berachain/bera-reth/issues/90
> test: add strict 30M gas limit regression test for PoL transactions

- src/transaction/pol.rs
- tests/e2e/coinbase_system_state_change_test.rs
- tests/e2e/gas_limit_regression_test.rs
- tests/e2e/mod.rs
- Adds e2e test to verify system calls can modify multiple accounts during execution
- Verifies that transfers to system address and coinbase persist correctly after alloy-rs/evm#121 fix
- Adds EIP-7002 system address regression test to prevent accidental address changes
- Refactors e2e test constants to shared module for reusability
Closes #82
> test: add coinbase and system state change test for PoL transactions

- Cargo.lock
- Cargo.toml
- README.md
Bumps the crate version to v1.0.0 for the first stable production release.
- Update version in `Cargo.toml` from `1.0.0-rc.10` to `1.0.0`
- Update README.md to remove development warnings and reflect production status
- Add production status badge
This marks bera-reth as production-ready and suitable for mainnet usage.
1. Create and push git tag: `git tag v1.0.0 && git push origin v1.0.0`
2. Monitor release workflow in Actions
3. Review and publish the generated release
> chore: bump version to 1.0.0

- src/chainspec/mod.rs
- src/genesis/mod.rs
- No berachain field → fallback to Ethereum behavior  
- berachain present but no prague1 → fallback to Ethereum behavior
- berachain and prague1 present → validate fully, panic if misconfigured
Closes #99
> fix: improve genesis parsing to handle missing berachain config gracefully

- .github/workflows/docker-nightly.yml
- .github/workflows/hive-rpc.yml
Adds automated GitHub issue creation when hive RPC tests detect regressions:
- Creates issues automatically when bera-reth fails different tests than reth:nightly  
- Includes reproduction steps and workflow links for debugging
- Coordinates timing: Docker nightly builds every 12 hours, hive tests 5 hours later
- Labels issues with 'hive' and 'regression' for easy tracking
This provides better visibility and tracking of RPC compatibility regressions.
> chore: add automated regression detection to hive CI

- src/consensus/mod.rs
- src/transaction/mod.rs
this simplifies the codebase significantly and was recommended by the reth team
> refactor: switch to using transaction signed

- .github/workflows/docker-nightly.yml
- .github/workflows/hive.yml
- .github/workflows/sync.yml
- src/chainspec/mod.rs
Adds automated sync tests that run nightly to verify bera-reth can sync both mainnet and bepolia networks.
- Matrix sync test workflow for mainnet (9M blocks) and bepolia (1M blocks)
- Dynamic genesis file and trusted peers fetching from beacon-kit
- Etherscan integration for sync verification
- Updated docker-nightly and hive to run daily at same time (1 AM UTC)
- Fixed chainspec to properly handle Berachain and BerachainBepolia chain IDs
> test: add nightly sync tests for mainnet and bepolia

- .github/workflows/hive.yml
- .github/workflows/sync.yml
The mainnet sync job got cancelled after 10hours. It's unclear why. Possible reasons are not enough disk space, timeout, etc. Reducing sync load and concurrency for better resource allocation.
Also adding an onfailure slack message
> fix: reduce mainnet sync load in CI
